"""add_subscriptions_table

Revision ID: 30a1e8607311
Revises: 22107c598e4a
Create Date: 2026-04-26 12:22:35.995348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a1e8607311'
down_revision: Union[str, Sequence[str], None] = '22107c598e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_pattern', sa.String(length=256), nullable=False),
    sa.Column('latest_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_charged', sa.Date(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('waste_score', sa.Integer(), nullable=True),
    sa.Column('waste_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
