"""add unique constraint on transactions date description amount

Revision ID: 3fe1e00972bd
Revises: 557538d29e41
Create Date: 2026-04-26 02:19:56.897552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe1e00972bd'
down_revision: Union[str, Sequence[str], None] = '557538d29e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transaction_date_description_amount', 'transactions', ['date', 'description', 'amount'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_date_description_amount', 'transactions', type_='unique')
    # ### end Alembic commands ###
