"""add transactions table

Revision ID: 557538d29e41
Revises: c0994c8fefdf
Create Date: 2026-04-26 02:03:51.953062

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '557538d29e41'
down_revision: str | Sequence[str] | None = 'c0994c8fefdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'TRANSPORT', 'SUBSCRIPTIONS', 'UTILITIES', 'ENTERTAINMENT', 'SAVINGS', 'HEALTHCARE', 'SHOPPING', 'INCOME', 'OTHER', name='transactioncategory'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
