"""initial

Revision ID: c0994c8fefdf
Revises:
Create Date: 2026-04-26 01:59:41.875663

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c0994c8fefdf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
